pipeline:
  testing:
    image: golang:1.9.2
    group: build
    commands:
      - make test
      - make fmt-check

  backend-1:
    image: golang
    group: build
    commands:
      - echo "sleep 5"
      - sleep 5
      - touch a.txt
      - ls
  backend-2:
    image: golang
    group: build
    secrets: [test_sc ]
        - source: test_sc
        - target: ttyy
    commands:
      - echo "sleep 15"
      - sleep 15
      - echo $TEST_SC
      - echo $TTYY
